### ISSUE TITLE
Crash: Open file choice window

### ISSUE THREAD

**Issue by 226776** [226776/pwr_dolby_group#18]
Envirounment version: 
conda version: 4.6.14
conda-build version: 3.17.8
python version: 3.6.8.final.0

Test: 
Open application>Click Tool Button to choose wave or mp3 file. 

Expected result: 
Window opens and waits for user to choose file. 

Result: 
App crashes while opening the file path choice window (few seconds after hitting tool button).

Note: 
Crash not always exist, depends on version of envirounment, and computer.

**Comment by MaczekO** [comment]
The fault is coming from PyCharm probably. Try running the script from anaconda prompt in the folder
`conda activate env
python GUI_X1_3.py`

**Comment by Obciu13** [comment]
In my case that worked pretty well.

**Comment by MaczekO** [comment]
Should be fully functional now - check it and close
